# Generated by Django 2.1.7 on 2019-02-12 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=10000)),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_master', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('description', models.CharField(max_length=10000)),
                ('campaign', models.ManyToManyField(to='mainapp.Campaign')),
                ('known_characters', models.ManyToManyField(to='mainapp.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=10000)),
                ('campaign', models.ManyToManyField(to='mainapp.Campaign')),
                ('important_characters', models.ManyToManyField(to='mainapp.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HISTORY', 'History'), ('ARCANE', 'Arcane'), ('LOC', 'Location'), ('CHAR', 'Character')], max_length=100)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text_level1', models.TextField(blank=True, null=True)),
                ('text_level2', models.TextField(blank=True, null=True)),
                ('text_level3', models.TextField(blank=True, null=True)),
                ('text_level4', models.TextField(blank=True, null=True)),
                ('campaign', models.ManyToManyField(to='mainapp.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='own_lore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Lore'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location'),
        ),
        migrations.AddField(
            model_name='character',
            name='known_locations',
            field=models.ManyToManyField(to='mainapp.Location'),
        ),
        migrations.AddField(
            model_name='character',
            name='known_lores',
            field=models.ManyToManyField(null=True, related_name='known_lores', to='mainapp.Lore'),
        ),
        migrations.AddField(
            model_name='character',
            name='own_lore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_lore', to='mainapp.Lore'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
