# Generated by Django 2.1.7 on 2019-10-25 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='game_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting', to='mainapp.Setting'),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(default='images/default_char.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='character',
            name='known_lores',
            field=models.ManyToManyField(blank=True, null=True, related_name='known_lores', through='mainapp.KnownLoreCharacter', to='mainapp.Lore'),
        ),
        migrations.AlterField(
            model_name='character',
            name='own_lore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_lore', to='mainapp.Lore'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='own_lore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Lore'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Location'),
        ),
    ]
