# Generated by Django 2.1.7 on 2019-10-25 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191025_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_log', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('game_master_log', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Campaign')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='known_lores',
            field=models.ManyToManyField(blank=True, related_name='known_lores', through='mainapp.KnownLoreCharacter', to='mainapp.Lore'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='charactersession',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Character'),
        ),
        migrations.AddField(
            model_name='charactersession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Session'),
        ),
        migrations.AddField(
            model_name='character',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='character_sessions', through='mainapp.CharacterSession', to='mainapp.Session'),
        ),
    ]
