# Generated by Django 2.1.7 on 2019-02-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='known_characters',
            field=models.ManyToManyField(null=True, to='main.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='known_locations',
            field=models.ManyToManyField(null=True, to='main.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='important_characters',
            field=models.ManyToManyField(null=True, to='main.Character'),
        ),
    ]
