# Generated by Django 2.1.7 on 2019-02-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190212_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='known_characters',
            field=models.ManyToManyField(blank=True, to='main.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='known_locations',
            field=models.ManyToManyField(blank=True, to='main.Location'),
        ),
        migrations.AlterField(
            model_name='character',
            name='known_lores',
            field=models.ManyToManyField(blank=True, related_name='known_lores', to='main.Lore'),
        ),
        migrations.AlterField(
            model_name='location',
            name='important_characters',
            field=models.ManyToManyField(blank=True, to='main.Character'),
        ),
    ]
